[package]
name = "trade"
version = "0.1.0"
authors = ["scalexm <martin.alex32@hotmail.fr>"]

[dependencies]
serde_json = "^1.0"
serde = "^1.0"
serde_derive = "^1.0"
futures = "0.1.17"
failure = "^0.1"
failure_derive = "^0.1"
hyper = "^0.12"
hyper-tls = "^0.2"
log = "^0.4"
env_logger = "^0.5"
num = "^0.1"
openssl = "^0.10"
hex = "^0.3"
tokio = "^0.1"
chrono = "^0.4"

[dependencies.ws]
version = "^0.7"
features = ["ssl"]
