[package]
name = "binance-prompt"
version = "0.1.0"
authors = ["scalexm <martin.alex32@hotmail.fr>"]

[dependencies]
futures = "0.1.17"
tokio = "^0.1"
cursive = "^0.8"
trade-rs = { path = "../" }
serde_json = "^1.0"