[package]
name = "api-prompt"
version = "0.1.0"
authors = ["scalexm <martin.alex32@hotmail.fr>"]

[dependencies]
futures = "0.1.17"
tokio = "^0.1"
cursive = "^0.8"
trade = { path = "../" }
serde_json = "^1"
failure = "^0.1"
env_logger = "^0.5"
clap = "^2"
